import "./globals.css";
import type { Metadata } from "next";
import { Roboto, Pacifico } from "next/font/google";
import AuthContext from "./AuthContext";
import LogoutButton from "./LogoutButton";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin", "latin-ext"],
});
const pacifico = Pacifico({
  weight: ["400"],
  variable: "--font-pacifico",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Budget Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} ${pacifico.variable}`}>
        <AuthContext>
          {/* <LogoutButton /> */}
          {children}
        </AuthContext>
      </body>
    </html>
  );
}
